add_test( Multiplicacao.TestDolarMultiplicacao [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=Multiplicacao.TestDolarMultiplicacao]==] --gtest_also_run_disabled_tests)
set_tests_properties( Multiplicacao.TestDolarMultiplicacao PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
add_test( Multiplicacao.TestFrancMultiplicacao [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=Multiplicacao.TestFrancMultiplicacao]==] --gtest_also_run_disabled_tests)
set_tests_properties( Multiplicacao.TestFrancMultiplicacao PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
add_test( TestEquality.EqualityBetweenCoins [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=TestEquality.EqualityBetweenCoins]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestEquality.EqualityBetweenCoins PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
add_test( TestCurrency.CheckCoinType [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=TestCurrency.CheckCoinType]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestCurrency.CheckCoinType PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
add_test( TestDifferentClassEquality.DifferentClassEquality [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=TestDifferentClassEquality.DifferentClassEquality]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestDifferentClassEquality.DifferentClassEquality PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
add_test( TestSimpleAddition.SimpleAddition [==[/home/luiz/Money_C++/test/money_test]==] [==[--gtest_filter=TestSimpleAddition.SimpleAddition]==] --gtest_also_run_disabled_tests)
set_tests_properties( TestSimpleAddition.SimpleAddition PROPERTIES WORKING_DIRECTORY [==[/home/luiz/Money_C++/test]==])
set( money_test_TESTS Multiplicacao.TestDolarMultiplicacao Multiplicacao.TestFrancMultiplicacao TestEquality.EqualityBetweenCoins TestCurrency.CheckCoinType TestDifferentClassEquality.DifferentClassEquality TestSimpleAddition.SimpleAddition)
